#1.Convert an integer to a floating-point number.

# a=int(input("Enter an integer:"))
# a=float(a)
# print("A floating point number is", a)

#2. Convert a float to an integer.

# b=float(input("Enter any floating number:"))
# b=int(b)
# print("The integer is",b)

#3. Convert an integer to a string.

# a=int(input("Enter an integer:"))
# a=str(a)
# print("The given string is", a)
# print(type(a))

#4. Convert a list to a tuple.

# list =[7,4,"Even", 56]
# list=tuple(list)
# print(type(list))
# print(list)

#5. Convert a tuple to a list.

# tup =(7,4,"Even", 56)
# tup=list(tup)
# print(type(tup))
# print(tup)

#6. Convert a decimal number to binary.

# a=int(input("Enter any decimal number:"))
# a=bin(a)
# print(type(a))
# print(a)

#7. Convert a non-zero number to boolean.

# n=int(input("Enter any non-zero number: "))
# n=bool(n)
# print(type(n))
# print(n)